#!/usr/bin/env ruby
#
#  SpreadOSD
#  Copyright (C) 2010  FURUHASHI Sadayuki
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

require 'spread'
require 'optparse'

include SpreadOSD

op = OptionParser.new
op.banner += " <config.yaml>"

(class<<self;self;end).module_eval do
	define_method(:usage) do |msg|
		puts op.to_s
		puts "error: #{msg}" if msg
		exit 1
	end
end

begin
	if ARGV.length != 1
		raise "<config.yaml> is required."
	end

	config_path = ARGV.shift

	MDSConfigService.init.read(config_path)

rescue
	usage($!.to_s)
end

MDSBootService.init
$ebus.signal(:run)

$ebus.connect(:shutdown) do
	$net.stop
end

$net.run

