#!/usr/bin/env ruby

require 'spread-client'

if ARGV.length != 1
	puts "usage: #{$0} <host:port>"
	exit 1
end

host, port = ARGV[0].split(':',2)

c = SpreadClient.new(host, port)


mid1 = c.add("k1", {"a"=>1}, "v1")
mid2 = c.add("k2", {"b"=>2}, "v2")
mid3 = c.add("k1/k3", {"c"=>3}, "v3")
mid4 = c.add("k1/k3/k4", {"d"=>4}, "v4")

p c.get("k1")
p c.get_attributes("k1")
p c.get_direct(mid1)

p c.get("k2")
p c.get_attributes("k2")
p c.get_direct(mid2)

p c.get("k1/k3")
p c.get_attributes("k1/k3")
p c.get_direct(mid3)

p c.get("k1/k3/k4")
p c.get_attributes("k1/k3/k4")
p c.get_direct(mid4)

p c.get("none")
p c.get_attributes("none")
p c.set_attributes("none", {"x"=>nil})

p c.get_child_keys("k1", 0, 100)

